name: fl_assets_picker
description: assets picker
version: 0.0.1

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  wechat_assets_picker: ^7.3.2
  wechat_camera_picker: ^3.4.0
  extended_image: ^6.2.1
  photo_manager: ^2.1.4
  video_player: ^2.4.5
  fl_video: ^1.0.1
  wakelock: ^0.6.2

dev_dependencies:
  flutter_lints: ^2.0.1
